<?php
function tadah_gift_entity_info() {
  $return = array(
    'tadah_gift' => array(
      'label' => t('Gift', array(), array('context' => 'a tadah gift')),
      // 'controller class' => 'CommerceOrderEntityController',
      'base table' => 'tadah_gift',
      // 'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'gift_id',
        'label' => 'name',
      ),
      /*
      'bundle keys' => array(
        'bundle' => 'type',
      ),
       */
      'bundles' => array(
        'tadah_gift' => array(
          'label' => t('Gift', array(), array('context' => 'a tadah gift')),
          'admin' => array(
            'path' => 'admin/structure/tadah_gift/manage',
            'access arguments' => array('administer gifts'),
          ),
          // 'admin' blah blah
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        ),
        /*
        'administrator' => array(
          'label' => t('Administrator'),
          'custom settings' => FALSE,
        ),
        'customer' => array(
          'label' => t('Customer'),
          'custom settings' => FALSE,
        ),
         */
      ),
    ),
  );

  return $return;
}

function tadah_gift_uri($gift){
  return array(
    'path' => 'tadah_gift/' . $gift->id,
  );
}

function tadah_gift_load($gift_id = NULL, $reset = FALSE){
  $gift_ids = (isset ($gift_id) ? array($gift_id) : array());
  $tadah_gift = tadah_gift_load_multiple($gift_ids, $reset);
  return $tadah_gift ? reset ($tadah_gift) : FALSE;
}

function tadah_gift_load_multiple($gift_ids = array(), $conditions = array(), $reset = FALSE){
  return entity_load('tadah_gift', $gift_ids, $conditions, $reset);
}

function tadah_gift_menu(){
  $items['admin/structure/tadah_gift/manage'] = array(
    'title' => 'tadah_gift Admin',
    'description' => 'Manage tadah_gift structure',
    'page callback' => 'tadah_gift_info',
    'access arguments' => array('administer tadah_gifts'),
  );
  $items['tadah_gift/%tadah_gift'] = array(
    'title callback' => 'tadah_gift_page_title',
    'title arguments' => array(1),
    'page callback' => 'tadah_gift_page_view',
    'page arguments' => array(1),
    'access arguments' => array('view tadah_gifts'),
    'type' => MENU_CALLBACK,
  );
  $items['tadah_gift/add'] = array(
    'title' => 'Add Gift!',
    'page callback' => 'tadah_gift_add',
    'access arguments' => array('create tadah_gift'),
  );
  $items['tadah_gift/select'] = array(
    'title' => 'Select Gift!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tadah_gift_select_form'),
    'file' => 'tadah_gift_select.inc',
    'access arguments' => array('select tadah_gift'),
  );
  return $items;
}

function tadah_gift_permission(){
    return array(
    'administer tadah_gifts' =>  array(
      'title' => t('Administer tadah_gifts'),
      'restrict access' => TRUE,
    ),
    'view tadah_gifts' => array(
      'title' => t('View tadah_gifts'),
    )
  );
}


function tadah_gift_info() {
  return ('Welcome to the administration page for your tadah_gifts!');
}

function tadah_gift_page_title($tadah_gift) {
  return $tadah_gift->gift_id;
}

function tadah_gift_page_view($tadah_gift, $view_mode = 'full') {
  $tadah_gift->content = array();

  // Build fields content.
  field_attach_prepare_view('tadah_gift', array($tadah_gift->gift_id => $tadah_gift), $view_mode);
  entity_prepare_view('tadah_gift', array($tadah_gift->gift_id => $tadah_gift));
  $tadah_gift->content += field_attach_view('tadah_gift', $tadah_gift, $view_mode);
  dpm($tadah_gift);

  return $tadah_gift->content;
}

function tadah_gift_markup($gift_id) {
	$gift = tadah_gift_load($gift_id);
	$markup = '<table><tr><td width="160px"><img src="'.$gift->picture_url.'" alt="'.$gift->name.'" width="160px"></td>';
	$markup .= '</td><td>';
	$markup .= '<table><tr><td width="100px">Name</td><td><h4><b>'.$gift->name.'</b></h4>  '.l('Product Detail', $gift->detail_url).'</td></tr>';
	$markup .= '<tr><td>Description</td><td>'.$gift->description.'</td></tr>';
	$markup .= '<tr><td>Price</td><td>'.$gift->price.'</td></tr>';
	$markup .= '<tr><td>Surprise Index</td><td>'.$gift->surprise_index.'</td></tr>';
	$markup .= '</table>';
	$markup .= '</td></tr></table>';
	return $markup;
}

/*
function tadah_gift_field_extra_fields() {
  $return = array();
  $return['tadah_gift']['tadah_gift'] = array(
    'form' => array(
      'note' => array(
        'label' => t('Note'),
        'description' => t('tadah_gift Note'),
      ),
    ),
  );

  return $return;
}
 */

function tadah_gift_add() {
  $tadah_gift = (object) array (
    'gift_id' => '',
  );

  return drupal_get_form('tadah_gift_add_form', $tadah_gift);
}


function tadah_gift_add_form($form, &$form_state, $tadah_gift) {
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
  );
  $form['price'] = array(
    '#type' => 'textfield',
    '#title' => t('Price'),
    '#required' => TRUE,
  );
  $form['picture_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Picture URL'),
    '#required' => TRUE,
  );
  $form['detail_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Detail URL'),
    '#required' => TRUE,
  );
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  // field_attach_form('tadah_gift', $tadah_gift, $form, $form_state);

  return $form;
}

function tadah_gift_add_form_validate($form, &$form_state) {
  $tadah_gift_submission = (object) $form_state['values'];
  // field_attach_form_validate('tadah_gift', $tadah_gift_submission, $form, $form_state);
}

function tadah_gift_add_form_submit($form, &$form_state) {
  $tadah_gift_submission = (object) $form_state['values'];
  // field_attach_submit('tadah_gift', $tadah_gift_submission, $form, $form_state);
  $tadah_gift = tadah_gift_save($tadah_gift_submission);
  $form_state['redirect'] = "tadah_gift/$tadah_gift->gift_id";
}

function tadah_gift_save(&$tadah_gift) {
  drupal_write_record('tadah_gift', $tadah_gift);
  // field_attach_insert('tadah_gift', $tadah_gift);
  module_invoke_all('entity_insert', 'tadah_gift', $tadah_gift);
  return $tadah_gift;
}



?>
